import { relative, dirname } from "node:path";
import type { Inventory, OutputRenderer, Project } from "../types.ts";

const MAX_CONTRIBUTIONS = 5;

export class MarkdownRenderer implements OutputRenderer {
  name = "markdown";

  render(inventory: Inventory, selectedIds: string[]): string {
    const selected = inventory.projects.filter(
      (p) => selectedIds.includes(p.id) && !p.tags.includes("removed")
    );

    if (selected.length === 0) {
      return "# Technical CV\n\n*No projects selected.*\n";
    }

    // Detect duplicate display names
    const nameCounts = new Map<string, number>();
    for (const p of selected) {
      nameCounts.set(p.displayName, (nameCounts.get(p.displayName) || 0) + 1);
    }

    const scanRoot = findCommonPrefix(selected.map((p) => p.path));

    // Generate summary from analyzed projects
    const summary = generateSummary(selected);

    // Group by year
    const byYear = new Map<string, Project[]>();
    for (const p of selected) {
      const year = getYear(p);
      if (!byYear.has(year)) byYear.set(year, []);
      byYear.get(year)!.push(p);
    }
    const sortedYears = [...byYear.keys()]
      .filter((y) => y !== "Unknown")
      .sort((a, b) => b.localeCompare(a));
    // Add Unknown at the end if exists
    if (byYear.has("Unknown")) sortedYears.push("Unknown");

    const lines: string[] = [
      "# Technical CV",
      "",
      `*Generated by agent-cv on ${new Date().toISOString().split("T")[0]}*`,
      "",
    ];

    // Summary section
    if (summary) {
      lines.push(summary, "");
    }

    lines.push("---", "");

    for (const year of sortedYears) {
      const projects = byYear.get(year)!;
      lines.push(`## ${year}`);
      lines.push("");

      for (const project of projects) {
        const isDuplicate = (nameCounts.get(project.displayName) || 0) > 1;
        lines.push(...renderProject(project, isDuplicate, scanRoot));
        lines.push("");
      }
    }

    // Footer
    const languages = countBy(selected, (p) => p.language);
    const sortedLangs = Object.entries(languages)
      .filter(([lang]) => lang !== "Unknown")
      .sort((a, b) => b[1] - a[1]);
    const dateRange = getOverallDateRange(selected);
    const frameworks = new Set<string>();
    for (const p of selected) {
      for (const fw of p.frameworks) frameworks.add(fw);
    }

    lines.push("---", "");
    const langStr = sortedLangs.slice(0, 5).map(([l]) => l).join(", ");
    lines.push(
      `**${selected.length} ${plural(selected.length, "project", "projects")}** | ${langStr}${sortedLangs.length > 5 ? ` +${sortedLangs.length - 5} more` : ""}`
    );
    if (dateRange) {
      lines.push(`${formatMonth(dateRange.start)} to ${formatMonth(dateRange.end)}`);
    }
    lines.push("");

    return lines.join("\n");
  }
}

/**
 * Auto-generate a 2-3 sentence summary of the developer based on their projects.
 */
function generateSummary(projects: Project[]): string {
  const languages = countBy(projects, (p) => p.language);
  const sortedLangs = Object.entries(languages)
    .filter(([lang]) => lang !== "Unknown")
    .sort((a, b) => b[1] - a[1]);

  const frameworks = new Map<string, number>();
  for (const p of projects) {
    for (const fw of p.frameworks) {
      frameworks.set(fw, (frameworks.get(fw) || 0) + 1);
    }
  }
  const topFrameworks = [...frameworks.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([fw]) => fw);

  const dateRange = getOverallDateRange(projects);
  const years = dateRange
    ? Math.max(1, new Date().getFullYear() - parseInt(dateRange.start.split("-")[0]!))
    : 0;

  const primaryLang = sortedLangs[0]?.[0] || "multiple languages";
  const secondaryLangs = sortedLangs.slice(1, 3).map(([l]) => l);

  let summary = `Full-stack developer with ${years}+ years of experience, primarily in ${primaryLang}`;
  if (secondaryLangs.length > 0) {
    summary += ` with additional work in ${secondaryLangs.join(" and ")}`;
  }
  summary += ".";

  if (topFrameworks.length > 0) {
    summary += ` Most frequent tools: ${topFrameworks.join(", ")}.`;
  }

  summary += ` ${projects.length} projects spanning ${sortedLangs.length} languages.`;

  return summary;
}

function renderProject(
  project: Project,
  isDuplicate: boolean,
  scanRoot: string
): string[] {
  const lines: string[] = [];
  const name = project.suggestedName || project.displayName;
  const dateStr = formatDateRange(project.dateRange);

  let title = name;
  if (isDuplicate) {
    const rel = relative(scanRoot, project.path);
    const parent = dirname(rel);
    if (parent && parent !== ".") {
      title = `${name} (${parent})`;
    }
  }

  lines.push(`### ${title}${dateStr ? ` — ${dateStr}` : ""}`);
  lines.push("");

  // Tech stack
  const tech = project.analysis?.techStack ?? [project.language];
  if (tech.length > 0) {
    lines.push(`**Tech:** ${tech.join(", ")}`);
    lines.push("");
  }

  // Summary (LLM analysis or fallback to manifest description)
  if (project.analysis?.summary) {
    lines.push(project.analysis.summary);
    lines.push("");
  } else if (project.description) {
    lines.push(project.description);
    lines.push("");
  }

  // Contributions (capped)
  if (project.analysis?.contributions && project.analysis.contributions.length > 0) {
    const contributions = project.analysis.contributions.slice(0, MAX_CONTRIBUTIONS);
    lines.push("**Key contributions:**");
    for (const c of contributions) {
      lines.push(`- ${c}`);
    }
    lines.push("");
  }

  // Metadata
  const meta: string[] = [];
  if (project.commitCount > 0) {
    meta.push(
      `${project.commitCount} ${plural(project.commitCount, "commit", "commits")}`
    );
  }
  if (project.authorCommitCount > 0 && project.authorCommitCount !== project.commitCount) {
    meta.push(`${project.authorCommitCount} by me`);
  }
  if (project.size.lines > 0) {
    const k = project.size.lines >= 1000
      ? `${(project.size.lines / 1000).toFixed(1)}K`
      : `${project.size.lines}`;
    meta.push(`${k} lines`);
  }
  if (project.remoteUrl) {
    // Clean GitHub URL for display
    const url = project.remoteUrl
      .replace(/\.git$/, "")
      .replace(/^git@github\.com:/, "https://github.com/");
    meta.push(`[repo](${url})`);
  }
  if (meta.length > 0) {
    lines.push(`*${meta.join(" | ")}*`);
    lines.push("");
  }

  return lines;
}

function getYear(project: Project): string {
  const date = project.dateRange.end || project.dateRange.start;
  if (!date) return "Unknown";
  return date.split("-")[0] || "Unknown";
}

function formatDateRange(range: { start: string; end: string; approximate: boolean }): string {
  if (!range.start && !range.end) return "";
  const prefix = range.approximate ? "~" : "";
  const start = formatMonth(range.start);
  const end = formatMonth(range.end);
  if (start === end) return `${prefix}${start}`;
  return `${prefix}${start} — ${end}`;
}

function formatMonth(dateStr: string): string {
  if (!dateStr) return "?";
  const [year, month] = dateStr.split("-");
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const monthName = months[parseInt(month || "0", 10) - 1] || month;
  return `${monthName} ${year}`;
}

function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many;
}

function countBy<T>(items: T[], key: (item: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const k = key(item);
    counts[k] = (counts[k] || 0) + 1;
  }
  return counts;
}

function getOverallDateRange(projects: Project[]): { start: string; end: string } | null {
  const starts = projects.map((p) => p.dateRange.start).filter(Boolean).sort();
  const ends = projects.map((p) => p.dateRange.end).filter(Boolean).sort();
  if (starts.length === 0) return null;
  return { start: starts[0]!, end: ends[ends.length - 1] || starts[0]! };
}

function findCommonPrefix(paths: string[]): string {
  if (paths.length === 0) return "";
  if (paths.length === 1) return dirname(paths[0]!);
  const parts = paths[0]!.split("/");
  let prefix = "";
  for (let i = 0; i < parts.length; i++) {
    const candidate = parts.slice(0, i + 1).join("/");
    if (paths.every((p) => p.startsWith(candidate + "/") || p === candidate)) {
      prefix = candidate;
    } else {
      break;
    }
  }
  return prefix;
}
